// Package go_GopherKit is an autogenerated binder stub for package GopherKit.
//   gobind -lang=go github.com/tomasen/gomobile-demo/sdk
//
// File is generated by gobind. Do not edit.
package go_GopherKit

import (
	"github.com/tomasen/gomobile-demo/sdk"
	"golang.org/x/mobile/bind/seq"
)

const (
	proxyCallback_Descriptor          = "go.GopherKit.Callback"
	proxyCallback_StateDidUpdate_Code = 0x10a
)

func proxyCallback_StateDidUpdate(out, in *seq.Buffer) {
	ref := in.ReadRef()
	v := ref.Get().(GopherKit.Callback)
	v.StateDidUpdate()
}

func init() {
	seq.Register(proxyCallback_Descriptor, proxyCallback_StateDidUpdate_Code, proxyCallback_StateDidUpdate)
}

type proxyCallback seq.Ref

func (p *proxyCallback) StateDidUpdate() {
	in := new(seq.Buffer)
	seq.Transact((*seq.Ref)(p), "go.GopherKit.Callback", proxyCallback_StateDidUpdate_Code, in)
}

func proxy_GetState(out, in *seq.Buffer) {
	res := GopherKit.GetState()
	out.WriteGoRef(res)
}

func proxy_RegisterCallback(out, in *seq.Buffer) {
	var param_c GopherKit.Callback
	param_c_ref := in.ReadRef()
	if param_c_ref.Num < 0 { // go object
		param_c = param_c_ref.Get().(GopherKit.Callback)
	} else { // foreign object
		param_c = (*proxyCallback)(param_c_ref)
	}
	GopherKit.RegisterCallback(param_c)
}

func proxy_Start(out, in *seq.Buffer) {
	GopherKit.Start()
}

const (
	proxyState_Descriptor             = "go.GopherKit.State"
	proxyState_NanoTimeStamp_Get_Code = 0x00f
	proxyState_NanoTimeStamp_Set_Code = 0x01f
	proxyState_Message_Get_Code       = 0x10f
	proxyState_Message_Set_Code       = 0x11f
)

type proxyState seq.Ref

func proxyState_NanoTimeStamp_Set(out, in *seq.Buffer) {
	ref := in.ReadRef()
	v := in.ReadInt64()
	ref.Get().(*GopherKit.State).NanoTimeStamp = v
}

func proxyState_NanoTimeStamp_Get(out, in *seq.Buffer) {
	ref := in.ReadRef()
	v := ref.Get().(*GopherKit.State).NanoTimeStamp
	out.WriteInt64(v)
}

func proxyState_Message_Set(out, in *seq.Buffer) {
	ref := in.ReadRef()
	v := in.ReadString()
	ref.Get().(*GopherKit.State).Message = v
}

func proxyState_Message_Get(out, in *seq.Buffer) {
	ref := in.ReadRef()
	v := ref.Get().(*GopherKit.State).Message
	out.WriteString(v)
}

func init() {
	seq.Register(proxyState_Descriptor, proxyState_NanoTimeStamp_Set_Code, proxyState_NanoTimeStamp_Set)
	seq.Register(proxyState_Descriptor, proxyState_NanoTimeStamp_Get_Code, proxyState_NanoTimeStamp_Get)
	seq.Register(proxyState_Descriptor, proxyState_Message_Set_Code, proxyState_Message_Set)
	seq.Register(proxyState_Descriptor, proxyState_Message_Get_Code, proxyState_Message_Get)
}

func init() {
	seq.Register("GopherKit", 1, proxy_GetState)
	seq.Register("GopherKit", 2, proxy_RegisterCallback)
	seq.Register("GopherKit", 3, proxy_Start)
}
