// Objective-C API for talking to github.com/tomasen/gomobile-demo/sdk Go package.
//   gobind -lang=objc github.com/tomasen/gomobile-demo/sdk
//
// File is generated by gobind. Do not edit.

#ifndef __GoGopherKit_H__
#define __GoGopherKit_H__

#include <Foundation/Foundation.h>

@class GoGopherKitState;
@protocol GoGopherKitCallback;
@class GoGopherKitCallback;

@interface GoGopherKitState : NSObject {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (int64_t)nanoTimeStamp;
- (void)setNanoTimeStamp:(int64_t)v;
- (NSString*)nanoCounter;
- (void)setNanoCounter:(NSString*)v;
@end

@protocol GoGopherKitCallback
- (void)stateDidUpdate;
@end

FOUNDATION_EXPORT GoGopherKitState* GoGopherKitGetState();

FOUNDATION_EXPORT void GoGopherKitRegisterCallback(id<GoGopherKitCallback> c);

FOUNDATION_EXPORT void GoGopherKitStart();

#endif
